version: "3.9"

services:
  flarum:
    build:
      context: ${PWD}
    image: flarum-custom
    container_name: flarum
    env_file:
      - .env
    environment:
      - PHP_EXTENSIONS=gmp session brotli
    # volumes:
      # - ${DEPLOY_DIR}/assets:/flarum/app/assets
      # - ${DEPLOY_DIR}/extensions:/flarum/app/extensions
      # - ${DEPLOY_DIR}/storage/logs:/flarum/app/storage/logs
      # - ${DEPLOY_DIR}/nginx:/etc/nginx/flarum
    ports:
      - 80:8888
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=666666
    volumes:
      - ${DATABASE_DIR}/db:/var/lib/mysql