name: Bug
description: 提交一个 Bug
title: "<title>"
labels: ["bug"]
body:
- type: textarea
  id: current
  attributes:
    label: 当前行为
    description: 简短地描述你当前遇到的问题。
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: 预期行为
    description: 简短地描述你期望的正确行为。
  validations:
    required: false
- type: textarea
  id: reprod
  attributes:
    label: 复现步骤
    description: 如何复现你遇到的问题。
    placeholder: |
      1. 前往 ... 页面
      2. 点击 ...
      3. 滚动到 ...
      4. 出现 ... 错误
  validations:
    required: false
- type: dropdown
  id: platform
  attributes:
    label: 平台信息
    multiple: true
    options:
      - PC
      - Android
      - iOS
      - 其他
  validations:
    required: true
- type: dropdown
  id: browser
  attributes:
    label: 浏览器信息
    multiple: true
    options:
      - Chrome
      - Firefox
      - Safari
      - Edge
      - 其他
  validations:
    required: true
- type: dropdown
  id: user
  attributes:
    label: 用户状态信息
    multiple: true
    options:
      - 未登录
      - 普通用户
      - 版主
      - 管理员
  validations:
    required: true
- type: textarea
  id: context
  attributes:
    label: 补充信息
    description: |
      链接、截图等等任何可能有帮助的补充信息。
      
      你可以点击该区域并拖动文件到此处来上传图片或日志。
  validations:
    required: false
